version: "3.3"

services:
  db:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "8000:8000"
        environment:
          - SERVER=127.0.0.1,1433
          - DATABASE=master
          - USERNAME=sa
          - PASSWORD=P@s5w0rd
          - DRIVER='{ODBC Driver 18 for SQL Server}'


